global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'metrics-reporter-example'
    static_configs:
      - targets: ['host.docker.internal:3000']
    scrape_interval: 5s
    metrics_path: /metrics